### ISSUE TITLE
Should mark .pch files readonly too.

### ISSUE THREAD

**Issue by brianpartridge** [Yelp/cocoapods-readonly#1]
If a podspec specifies a `.pch` file via `prefix_header_file` it does not get marked readonly.

`s.prefix_header_file = "SquareData/SquareData-Prefix.pch"`

`-rw-r--r--  1 brianpartridge  brianpartridge    584 Apr 15 15:29 Pods/SquareData/SquareData/SquareData-Prefix.pch`

**Comment by mglidden** [comment]
Good catch! Those are even more important to lock, since editing them won't update the code that actually gets compiled (pch files are appended to a different pch file instead of linked with the rest of the source files).

Version 1.0.1 locks all files related to the pod (including pch, the license, and source files)

**Comment by brianpartridge** [comment]
Tested & working. Thanks.
